export const APP_REGISTRY = [
  {
    id: "wyloni",
    name: "Wyloni",
    description: "Assistente AI per cittadini italiani: bandi, fondi, tutela consumatori, immobiliare",
    icon: "🇮🇹",
    status: "connected" as const,
    domains: ["wyloni_bandi", "pratica_legal"],
    connectedAt: "2026-01-15",
    platform: "PWA Mobile",
    color: "violet" as const,
  },
  {
    id: "keydraft",
    name: "KeyDraft",
    description: "Scanner immobiliare AI: aste, luxury, off-market",
    icon: "🏠",
    status: "connected" as const,
    domains: ["keydraft_realestate"],
    connectedAt: "2026-02-10",
    platform: "PWA Mobile",
    color: "cyan" as const,
  },
];

export const TASK_REGISTRY = [
  { task: "search_grants", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "deep_search", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "distress_radar", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "market_glitch", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "deep_recovery", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "find_contacts", provider: "Perplexity", domains: ["pratica_legal"], maxTokens: 1200, type: "web" as const },
  { task: "find_company_contacts", provider: "Perplexity", domains: ["pratica_legal"], maxTokens: 1200, type: "web" as const },
  { task: "real_estate_deep", provider: "Perplexity", domains: ["keydraft_realestate"], maxTokens: 1800, type: "web" as const },
  { task: "ai_bandi", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 2000, type: "web" as const },
  { task: "translate_objection", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "simplex", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "contratto_analisi", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 2000, type: "generative" as const },
  { task: "feasibility_lab", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 2000, type: "generative" as const },
  { task: "solve_problem", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "viral_content", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 1500, type: "generative" as const },
  { task: "viral_content_bundle", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 2500, type: "generative" as const },
  { task: "strategic_report", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 1500, type: "generative" as const },
  { task: "alchemist", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1600, type: "generative" as const },
  { task: "loyalty_analyze", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "batch_viral_content", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 1500, type: "generative" as const },
];

export const PROVIDERS = [
  {
    id: "openai",
    name: "OpenAI",
    model: "gpt-4o-mini",
    status: "active" as const,
    description: "Usato per task generativi, fallback Anthropic",
    envVar: "OPENAI_API_KEY",
    color: "emerald" as const,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    model: "claude-3-haiku-20240307",
    status: "active" as const,
    description: "Fallback quando OpenAI non risponde",
    envVar: "ANTHROPIC_API_KEY",
    color: "emerald" as const,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    model: "sonar",
    status: "active" as const,
    description: "Ricerca web reale per WEB_TASKS",
    envVar: "PERPLEXITY_API_KEY",
    color: "emerald" as const,
  },
];
