export type AppLifecycle = "attiva" | "principale" | "legacy" | "secondaria" | "sospesa" | "archivio";

export const APP_REGISTRY = [
  {
    id: "acquisitionradar",
    name: "AcquisitionRadar",
    description: "Radar acquisizioni immobiliari: ribassi, aste, gap OMI, segnali urbani",
    icon: "📡",
    status: "connected" as const,
    lifecycle: "attiva" as AppLifecycle,
    domains: ["civiko_radar_veneto"],
    connectedAt: "2026-05-01",
    platform: "Core endpoint",
    color: "violet" as const,
    coreEndpoint: "/functions/v1/civiko-radar-veneto",
    diagnosticsPath: "/provider-diagnostics",
  },
  {
    id: "wyloni",
    name: "Wyloni",
    description: "Assistente per cittadini italiani: bandi, fondi, tutela consumatori",
    icon: "🇮🇹",
    status: "connected" as const,
    lifecycle: "attiva" as AppLifecycle,
    domains: ["wyloni_bandi", "pratica_legal"],
    connectedAt: "2026-01-15",
    platform: "PWA Mobile",
    color: "violet" as const,
    diagnosticsPath: "/provider-diagnostics",
  },
  {
    id: "luxuradar",
    name: "LuxuRadar",
    description: "Radar luxury real estate e special situations (≥€3M)",
    icon: "💎",
    status: "connected" as const,
    lifecycle: "attiva" as AppLifecycle,
    domains: ["luxuradar"],
    connectedAt: "2026-05-24",
    platform: "Core endpoint",
    color: "amber" as const,
    coreEndpoint: "/functions/v1/luxuradar-scan",
    diagnosticsPath: "/provider-diagnostics",
  },
  {
    id: "civiko_one",
    name: "Metodo Civiko One",
    description: "PWA agenzie immobiliari — territorio pilota Padova e provincia",
    icon: "🏛️",
    status: "connected" as const,
    lifecycle: "archivio" as AppLifecycle,
    domains: ["civiko_one"],
    connectedAt: "2026-05-13",
    platform: "PWA Agenzie",
    color: "violet" as const,
    previewUrl: "https://civiko-method-pro.lovable.app",
    repository: "https://github.com/gheocapaula1000-code/civiko-method-pro",
    backendRef: "jpunnzgixcghuydstdlt",
    pilotTerritory: "Padova e provincia",
  },
  {
    id: "veneto_prestige",
    name: "Veneto Prestige",
    description: "Progetto sperimentale prestige Veneto — non completato",
    icon: "🏘️",
    status: "connected" as const,
    lifecycle: "archivio" as AppLifecycle,
    domains: ["veneto_prestige"],
    connectedAt: "2026-04-10",
    platform: "Sperimentale",
    color: "violet" as const,
  },
  {
    id: "keydraft",
    name: "KeyDraft",
    description: "Scanner immobiliare: aste, luxury, off-market",
    icon: "🏠",
    status: "connected" as const,
    lifecycle: "archivio" as AppLifecycle,
    domains: ["keydraft_realestate"],
    connectedAt: "2026-02-10",
    platform: "PWA Mobile",
    color: "cyan" as const,
  },
  {
    id: "sottra",
    name: "Sottra",
    description: "Scanner edifici: dati catastali, prezzi, energia, previsioni di zona",
    icon: "🏢",
    status: "connected" as const,
    lifecycle: "archivio" as AppLifecycle,
    domains: ["sottra"],
    connectedAt: "2026-03-05",
    platform: "PWA Mobile",
    color: "amber" as const,
  },
  {
    id: "regiads",
    name: "Regiads",
    description: "Progetto legacy advertising regionale",
    icon: "📰",
    status: "connected" as const,
    lifecycle: "archivio" as AppLifecycle,
    domains: ["regiads"],
    connectedAt: "2026-02-01",
    platform: "Legacy",
    color: "cyan" as const,
  },
  {
    id: "deep_source_core",
    name: "Deep Source Core",
    description: "Esperimento orchestrazione sorgenti profonde — non completato",
    icon: "🧪",
    status: "connected" as const,
    lifecycle: "archivio" as AppLifecycle,
    domains: ["deep_source_core"],
    connectedAt: "2026-03-20",
    platform: "Sperimentale",
    color: "violet" as const,
  },
];

export const TASK_REGISTRY = [
  { task: "search_grants", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "deep_search", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 1500, type: "web" as const },
  { task: "find_contacts", provider: "Perplexity", domains: ["pratica_legal"], maxTokens: 1200, type: "web" as const },
  { task: "find_company_contacts", provider: "Perplexity", domains: ["pratica_legal"], maxTokens: 1200, type: "web" as const },
  { task: "ai_bandi", provider: "Perplexity", domains: ["wyloni_bandi"], maxTokens: 2000, type: "web" as const },
  { task: "translate_objection", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "simplex", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "contratto_analisi", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 2000, type: "generative" as const },
  { task: "feasibility_lab", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 2000, type: "generative" as const },
  { task: "solve_problem", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "viral_content", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 1500, type: "generative" as const },
  { task: "viral_content_bundle", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 2500, type: "generative" as const },
  { task: "strategic_report", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 1500, type: "generative" as const },
  { task: "alchemist", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1600, type: "generative" as const },
  { task: "loyalty_analyze", provider: "OpenAI → Anthropic", domains: ["pratica_legal"], maxTokens: 1200, type: "generative" as const },
  { task: "batch_viral_content", provider: "OpenAI → Anthropic", domains: ["wyloni_bandi"], maxTokens: 1500, type: "generative" as const },
  { task: "keydraft_engine", provider: "OpenAI → Anthropic", domains: ["keydraft_realestate"], maxTokens: 2500, type: "generative" as const },
];

export const PROVIDERS = [
  {
    id: "openai",
    name: "OpenAI",
    model: "Configurazione runtime",
    status: "configured" as const,
    description: "Provider operativo per task generativi — fallback Anthropic",
    envVar: "OPENAI_API_KEY",
    color: "emerald" as const,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    model: "Configurazione runtime",
    status: "configured" as const,
    description: "Provider operativo di fallback",
    envVar: "ANTHROPIC_API_KEY",
    color: "emerald" as const,
  },
  {
    id: "perplexity",
    name: "Perplexity",
    model: "sonar",
    status: "configured" as const,
    description: "Ricerca web reale per task web",
    envVar: "PERPLEXITY_API_KEY",
    color: "emerald" as const,
  },
];
