export const VENETO_COMUNI: Record<string,string> = {
  // ── Canonical entries added for Geoportale recovery (accents/apostrophes/suffixes) ──
  "Albaredo d'Adige": "VR",
  "Boschi Sant'Anna": "VR",
  "Brenzone Sul Garda": "VR",
  "Costermano Sul Garda": "VR",
  // (Ferrara Di Monte Baldo già presente più sotto)
  "Roverè Veronese": "VR",
  "San Martino Buon Albergo": "VR",
  "Romano d'Ezzelino": "VI",
  // ── /canonical extensions ──
  "Abano Terme": "PD",
  "Adria": "RO",
  "Affi": "VR",
  "Agna": "PD",
  "Agordo": "BL",
  "Agugliaro": "VI",
  "Albettone": "VI",
  "Albignasego": "PD",
  "Alleghe": "BL",
  "Alonte": "VI",
  "Alpago": "BL",
  "Altavilla Vicentina": "VI",
  "Altissimo": "VI",
  "Altivole": "TV",
  "Angiari": "VR",
  "Anguillara Veneta": "PD",
  "Annone Veneto": "VE",
  "Arcade": "TV",
  "Arcole": "VR",
  "Arcugnano": "VI",
  "Ariano Nel Polesine": "RO",
  "Arre": "PD",
  "Arsiero": "VI",
  "Arzergrande": "PD",
  "Arzignano": "VI",
  "Asiago": "VI",
  "Asigliano Veneto": "VI",
  "Asolo": "TV",
  "Auronzo Di Cadore": "BL",
  "Badia Calavena": "VR",
  "Badia Polesine": "RO",
  "Bagnoli Di Sopra": "PD",
  "Bagnolo Di Po": "RO",
  "Baone": "PD",
  "Barbarano Mossano": "VI",
  "Barbona": "PD",
  "Bardolino": "VR",
  "Bassano Del Grappa": "VI",
  "Battaglia Terme": "PD",
  "Belfiore": "VR",
  "Belluno": "BL",
  "Bergantino": "RO",
  "Bevilacqua": "VR",
  "Boara Pisani": "PD",
  "Bolzano Vicentino": "VI",
  "Bonavigo": "VR",
  "Borca Di Cadore": "BL",
  "Borgo Valbelluna": "BL",
  "Borgo Veneto": "PD",
  "Borgoricco": "PD",
  "Borso Del Grappa": "TV",
  "Bosaro": "RO",
  "Bosco Chiesanuova": "VR",
  "Bovolenta": "PD",
  "Bovolone": "VR",
  "Breda Di Piave": "TV",
  "Breganze": "VI",
  "Brendola": "VI",
  "Brentino Belluno": "VR",
  "Bressanvido": "VI",
  "Brogliano": "VI",
  "Brugine": "PD",
  "Bussolengo": "VR",
  "Buttapietra": "VR",
  "Cadoneghe": "PD",
  "Caerano Di San Marco": "TV",
  "Calalzo Di Cadore": "BL",
  "Caldiero": "VR",
  "Caldogno": "VI",
  "Calto": "RO",
  "Caltrano": "VI",
  "Calvene": "VI",
  "Camisano Vicentino": "VI",
  "Campagna Lupia": "VE",
  "Campiglia Dei Berici": "VI",
  "Campo San Martino": "PD",
  "Campodarsego": "PD",
  "Campodoro": "PD",
  "Campolongo Maggiore": "VE",
  "Camponogara": "VE",
  "Camposampiero": "PD",
  "Canaro": "RO",
  "Canda": "RO",
  "Candiana": "PD",
  "Caorle": "VE",
  "Cappella Maggiore": "TV",
  "Caprino Veronese": "VR",
  "Carbonera": "TV",
  "Carceri": "PD",
  "Carmignano Di Brenta": "PD",
  "Cartigliano": "VI",
  "Cartura": "PD",
  "Casale Di Scodosia": "PD",
  "Casale Sul Sile": "TV",
  "Casaleone": "VR",
  "Casalserugo": "PD",
  "Casier": "TV",
  "Cassola": "VI",
  "Castagnaro": "VR",
  "Castegnero": "VI",
  "Castelbaldo": "PD",
  "Castelcucco": "TV",
  "Castelfranco Veneto": "TV",
  "Castelgomberto": "VI",
  "Castelguglielmo": "RO",
  "Castello Di Godego": "TV",
  "Castelmassa": "RO",
  "Cavaion Veronese": "VR",
  "Cavallino-Treporti": "VE",
  "Cavarzere": "VE",
  "Cavaso Del Tomba": "TV",
  "Cazzano Di Tramigna": "VR",
  "Ceggia": "VE",
  "Cencenighe Agordino": "BL",
  "Ceneselli": "RO",
  "Cerea": "VR",
  "Ceregnano": "RO",
  "Cerro Veronese": "VR",
  "Cervarese Santa Croce": "PD",
  "Cesiomaggiore": "BL",
  "Cessalto": "TV",
  "Chiampo": "VI",
  "Chiarano": "TV",
  "Chioggia": "VE",
  "Chiuppano": "VI",
  "Cibiana Di Cadore": "BL",
  "Cimadolmo": "TV",
  "Cinto Caomaggiore": "VE",
  "Cinto Euganeo": "PD",
  "Cison Di Valmarino": "TV",
  "Cittadella": "PD",
  "Codevigo": "PD",
  "Cogollo Del Cengio": "VI",
  "Colceresa": "VI",
  "Colle Santa Lucia": "BL",
  "Colle Umberto": "TV",
  "Cologna Veneta": "VR",
  "Colognola Ai Colli": "VR",
  "Comelico Superiore": "BL",
  "Cona": "VE",
  "Concamarise": "VR",
  "Concordia Sagittaria": "VE",
  "Conegliano": "TV",
  "Conselve": "PD",
  "Corbola": "RO",
  "Cordignano": "TV",
  "Cornedo Vicentino": "VI",
  "Cornuda": "TV",
  "Correzzola": "PD",
  "Costa Di Rovigo": "RO",
  "Costabissara": "VI",
  "Creazzo": "VI",
  "Crespadoro": "VI",
  "Crespino": "RO",
  "Crocetta Del Montello": "TV",
  "Curtarolo": "PD",
  "Danta Di Cadore": "BL",
  "Dolo": "VE",
  "Domegge Di Cadore": "BL",
  "Due Carrare": "PD",
  "Dueville": "VI",
  "Enego": "VI",
  "Eraclea": "VE",
  "Erbezzo": "VR",
  "Este": "PD",
  "Falcade": "BL",
  "Fara Vicentino": "VI",
  "Farra Di Soligo": "TV",
  "Feltre": "BL",
  "Ferrara Di Monte Baldo": "VR",
  "Ficarolo": "RO",
  "Fiesso Umbertiano": "RO",
  "Follina": "TV",
  "Fontanelle": "TV",
  "Fontaniva": "PD",
  "Fonte": "TV",
  "Fonzaso": "BL",
  "Fossalta Di Piave": "VE",
  "Fossalta Di Portogruaro": "VE",
  "Foza": "VI",
  "Frassinelle Polesine": "RO",
  "Fratta Polesine": "RO",
  "Fregona": "TV",
  "Fumane": "VR",
  "Gaiarine": "TV",
  "Gaiba": "RO",
  "Galliera Veneta": "PD",
  "Gallio": "VI",
  "Galzignano Terme": "PD",
  "Gambellara": "VI",
  "Garda": "VR",
  "Gavello": "RO",
  "Gazzo Veronese": "VR",
  "Giavera Del Montello": "TV",
  "Gorgo Al Monticano": "TV",
  "Gosaldo": "BL",
  "Grantorto": "PD",
  "Granze": "PD",
  "Grezzana": "VR",
  "Grisignano Di Zocco": "VI",
  "Gruaro": "VE",
  "Grumolo Delle Abbadesse": "VI",
  "Guarda Veneta": "RO",
  "Illasi": "VR",
  "Isola Della Scala": "VR",
  "Isola Rizza": "VR",
  "Isola Vicentina": "VI",
  "Istrana": "TV",
  "Jesolo": "VE",
  "La Valle Agordina": "BL",
  "Laghi": "VI",
  "Lamon": "BL",
  "Lastebasse": "VI",
  "Lavagno": "VR",
  "Lazise": "VR",
  "Legnago": "VR",
  "Legnaro": "PD",
  "Lendinara": "RO",
  "Limana": "BL",
  "Limena": "PD",
  "Longare": "VI",
  "Longarone": "BL",
  "Lonigo": "VI",
  "Loreggia": "PD",
  "Lorenzago Di Cadore": "BL",
  "Loreo": "RO",
  "Loria": "TV",
  "Lozzo Atestino": "PD",
  "Lozzo Di Cadore": "BL",
  "Lugo Di Vicenza": "VI",
  "Lusia": "RO",
  "Lusiana Conco": "VI",
  "Malcesine": "VR",
  "Malo": "VI",
  "Marano Di Valpolicella": "VR",
  "Marano Vicentino": "VI",
  "Marcon": "VE",
  "Mareno Di Piave": "TV",
  "Marostica": "VI",
  "Martellago": "VE",
  "Maser": "TV",
  "Maserada Sul Piave": "TV",
  "Masi": "PD",
  "Massanzago": "PD",
  "Meduna Di Livenza": "TV",
  "Megliadino San Vitale": "PD",
  "Melara": "RO",
  "Meolo": "VE",
  "Merlara": "PD",
  "Mestrino": "PD",
  "Mezzane Di Sotto": "VR",
  "Miane": "TV",
  "Minerbe": "VR",
  "Mira": "VE",
  "Mirano": "VE",
  "Mogliano Veneto": "TV",
  "Monastier Di Treviso": "TV",
  "Monfumo": "TV",
  "Monselice": "PD",
  "Montagnana": "PD",
  "Monte Di Malo": "VI",
  "Montebello Vicentino": "VI",
  "Montebelluna": "TV",
  "Montecchia Di Crosara": "VR",
  "Montecchio Maggiore": "VI",
  "Montecchio Precalcino": "VI",
  "Montegalda": "VI",
  "Montegaldella": "VI",
  "Montegrotto Terme": "PD",
  "Monteviale": "VI",
  "Monticello Conte Otto": "VI",
  "Montorso Vicentino": "VI",
  "Morgano": "TV",
  "Moriago Della Battaglia": "TV",
  "Motta Di Livenza": "TV",
  "Mozzecane": "VR",
  "Musile Di Piave": "VE",
  "Mussolente": "VI",
  "Nanto": "VI",
  "Nervesa Della Battaglia": "TV",
  "Noale": "VE",
  "Nogara": "VR",
  "Nogarole Rocca": "VR",
  "Nogarole Vicentino": "VI",
  "Nove": "VI",
  "Noventa Di Piave": "VE",
  "Noventa Padovana": "PD",
  "Noventa Vicentina": "VI",
  "Occhiobello": "RO",
  "Oderzo": "TV",
  "Oppeano": "VR",
  "Orgiano": "VI",
  "Ormelle": "TV",
  "Orsago": "TV",
  "Ospedaletto Euganeo": "PD",
  "Ospitale Di Cadore": "BL",
  "Padova": "PD",
  "Paese": "TV",
  "Papozze": "RO",
  "Pastrengo": "VR",
  "Pedavena": "BL",
  "Pederobba": "TV",
  "Perarolo Di Cadore": "BL",
  "Pernumia": "PD",
  "Pescantina": "VR",
  "Peschiera Del Garda": "VR",
  "Pettorazza Grimani": "RO",
  "Pianezze": "VI",
  "Pianiga": "VE",
  "Piazzola Sul Brenta": "PD",
  "Pieve Del Grappa": "TV",
  "Pieve Di Cadore": "BL",
  "Pieve Di Soligo": "TV",
  "Pincara": "RO",
  "Piombino Dese": "PD",
  "Piove Di Sacco": "PD",
  "Polesella": "RO",
  "Polverara": "PD",
  "Ponso": "PD",
  "Ponte Di Piave": "TV",
  "Ponte Nelle Alpi": "BL",
  "Pontecchio Polesine": "RO",
  "Pontelongo": "PD",
  "Ponzano Veneto": "TV",
  "Porto Tolle": "RO",
  "Porto Viro": "RO",
  "Portogruaro": "VE",
  "Posina": "VI",
  "Possagno": "TV",
  "Pove Del Grappa": "VI",
  "Povegliano": "TV",
  "Povegliano Veronese": "VR",
  "Pozzoleone": "VI",
  "Pozzonovo": "PD",
  "Pramaggiore": "VE",
  "Preganziol": "TV",
  "Pressana": "VR",
  "Quinto Di Treviso": "TV",
  "Quinto Vicentino": "VI",
  "Recoaro Terme": "VI",
  "Refrontolo": "TV",
  "Resana": "TV",
  "Revine Lago": "TV",
  "Riese Pio X": "TV",
  "Rivamonte Agordino": "BL",
  "Rivoli Veronese": "VR",
  "Roana": "VI",
  "Rocca Pietore": "BL",
  "Roncade": "TV",
  "Rosolina": "RO",
  "Rossano Veneto": "VI",
  "Rotzo": "VI",
  "Roverchiara": "VR",
  "Rovigo": "RO",
  "Rovolon": "PD",
  "Rubano": "PD",
  "Saccolongo": "PD",
  "Salara": "RO",
  "Salcedo": "VI",
  "Salgareda": "TV",
  "Salizzole": "VR",
  "Salzano": "VE",
  "San Bellino": "RO",
  "San Biagio Di Callalta": "TV",
  "San Bonifacio": "VR",
  "San Fior": "TV",
  "San Giorgio In Bosco": "PD",
  "San Giovanni Ilarione": "VR",
  "San Giovanni Lupatoto": "VR",
  "San Gregorio Nelle Alpi": "BL",
  "San Martino Di Lupari": "PD",
  "San Martino Di Venezze": "RO",
  "San Mauro Di Saline": "VR",
  "San Pietro Di Cadore": "BL",
  "San Pietro Di Feletto": "TV",
  "San Pietro Di Morubio": "VR",
  "San Pietro In Cariano": "VR",
  "San Pietro In Gu": "PD",
  "San Pietro Mussolino": "VI",
  "San Pietro Viminario": "PD",
  "San Polo Di Piave": "TV",
  "San Tomaso Agordino": "BL",
  "San Vendemiano": "TV",
  "San Vito Di Cadore": "BL",
  "San Vito Di Leguzzano": "VI",
  "San Zeno Di Montagna": "VR",
  "Sandrigo": "VI",
  "Sanguinetto": "VR",
  "Santa Giustina": "BL",
  "Santa Giustina In Colle": "PD",
  "Santa Lucia Di Piave": "TV",
  "Santa Maria Di Sala": "VE",
  "Santo Stefano Di Cadore": "BL",
  "Santorso": "VI",
  "Saonara": "PD",
  "Sarcedo": "VI",
  "Sarego": "VI",
  "Sarmede": "TV",
  "Schiavon": "VI",
  "Schio": "VI",
  "Sedico": "BL",
  "Segusino": "TV",
  "Selva Di Cadore": "BL",
  "Selva Di Progno": "VR",
  "Selvazzano Dentro": "PD",
  "Seren Del Grappa": "BL",
  "Setteville": "BL",
  "Silea": "TV",
  "Soave": "VR",
  "Solagna": "VI",
  "Solesino": "PD",
  "Sommacampagna": "VR",
  "Sona": "VR",
  "Sospirolo": "BL",
  "Sossano": "VI",
  "Soverzene": "BL",
  "Sovizzo": "VI",
  "Sovramonte": "BL",
  "Spinea": "VE",
  "Spresiano": "TV",
  "Stanghella": "PD",
  "Stienta": "RO",
  "Stra": "VE",
  "Susegana": "TV",
  "Taglio Di Po": "RO",
  "Taibon Agordino": "BL",
  "Tambre": "BL",
  "Tarzo": "TV",
  "Teglio Veneto": "VE",
  "Teolo": "PD",
  "Terrassa Padovana": "PD",
  "Terrazzo": "VR",
  "Tezze Sul Brenta": "VI",
  "Thiene": "VI",
  "Tombolo": "PD",
  "Tonezza Del Cimone": "VI",
  "Torre Di Mosto": "VE",
  "Torrebelvicino": "VI",
  "Torreglia": "PD",
  "Torri Del Benaco": "VR",
  "Torri Di Quartesolo": "VI",
  "Trebaseleghe": "PD",
  "Trecenta": "RO",
  "Tregnago": "VR",
  "Trevenzuolo": "VR",
  "Trevignano": "TV",
  "Treviso": "TV",
  "Tribano": "PD",
  "Trissino": "VI",
  "Urbana": "PD",
  "Val Di Zoldo": "BL",
  "Val Liona": "VI",
  "Valbrenta": "VI",
  "Valdagno": "VI",
  "Valdastico": "VI",
  "Valdobbiadene": "TV",
  "Valeggio Sul Mincio": "VR",
  "Vallada Agordina": "BL",
  "Valle Di Cadore": "BL",
  "Valli Del Pasubio": "VI",
  "Vazzola": "TV",
  "Vedelago": "TV",
  "Veggiano": "PD",
  "Velo Veronese": "VR",
  "Venezia": "VE",
  "Verona": "VR",
  "Veronella": "VR",
  "Vescovana": "PD",
  "Vestenanova": "VR",
  "Vicenza": "VI",
  "Vidor": "TV",
  "Vigasio": "VR",
  "Vigo Di Cadore": "BL",
  "Vigodarzere": "PD",
  "Vigonovo": "VE",
  "Vigonza": "PD",
  "Villa Bartolomea": "VR",
  "Villa Del Conte": "PD",
  "Villa Estense": "PD",
  "Villadose": "RO",
  "Villafranca Di Verona": "VR",
  "Villafranca Padovana": "PD",
  "Villaga": "VI",
  "Villamarzana": "RO",
  "Villanova Del Ghebbo": "RO",
  "Villanova Marchesana": "RO",
  "Villaverla": "VI",
  "Villorba": "TV",
  "Vittorio Veneto": "TV",
  "Volpago Del Montello": "TV",
  "Voltago Agordino": "BL",
  "Zenson Di Piave": "TV",
  "Zermeghedo": "VI",
  "Zero Branco": "TV",
  "Zevio": "VR",
  "Zimella": "VR",
  "Zovencedo": "VI",
  "Zugliano": "VI"
};
