INSERT INTO public.civiko_source_registry
  (source_code, source_name, source_url, refresh_frequency, access_type, compliance_level, implementation_status, notes)
VALUES
  ('F1',  'OMI - Osservatorio Mercato Immobiliare (Agenzia Entrate)', 'https://www.agenziaentrate.gov.it/portale/web/guest/schede/fabbricatiterreni/omi', 'semestrale', 'public_file', 'public', 'live',          'Baseline prezzi/quote OMI per microzona. Import via omi-import.'),
  ('F2',  'ISTAT SDMX - Demografia Veneto',                            'https://sdmx.istat.it',                                                          'annuale',    'public_api',  'public', 'live',          'Edge function istat-sdmx-fetch popola istat_comuni (75-84, 85+, indice vecchiaia).'),
  ('F5',  'OpenStreetMap - Overpass cantieri/infrastrutture',          'https://overpass-api.de',                                                        'on_demand',  'public_api',  'public', 'live',          'connector-osm-cantieri.'),
  ('F6',  'ISPRA - Dissesto idrogeologico / consumo suolo',            'https://www.isprambiente.gov.it/',                                              'annuale',    'public_file', 'public', 'partial',       'Import tramite istat-ispra-import.'),
  ('F7',  'ARPAV - Qualità aria Padova',                                'https://www.arpa.veneto.it/',                                                    'giornaliera','public_api',  'public', 'live',          'Job import-arpav-air-quality → microzone_sentiment (score 0-100, no PM numerici).'),
  ('F8',  'MIM - Scuole statali',                                       'https://dati.istruzione.it/opendata/',                                          'annuale',    'public_file', 'public', 'live',          'mim_schools popolato via openapi/import job.'),
  ('F9',  'Infratel - Banda ultra-larga',                               'https://bandaultralarga.italia.it/',                                            'trimestrale','public_file', 'public', 'partial',       'Precisione civic-level dichiarata, vedi memoria sottra-education-connectivity.'),
  ('F10', 'ANAC - Contratti pubblici',                                  'https://dati.anticorruzione.it/',                                                'mensile',    'public_api',  'public', 'planned',       'Pianificato: cantieri/appalti su area Padova.'),
  ('F11', 'OpenPNRR - Interventi PNRR territorio',                      'https://www.openpnrr.it/',                                                       'mensile',    'public_api',  'public', 'live',          'civiko-pnrr-padova.'),
  ('F13', 'Immobiliare.it - Listings (gateway Apify)',                  'https://www.immobiliare.it/',                                                    'on_demand',  'scraping',    'sensitive_aggregate', 'partial', 'Solo aggregati di zona via Apify allow-listed. No PII.'),
  ('F14', 'OpenAPI.it - Catasto / visure',                              'https://catasto.openapi.it/',                                                    'on_demand',  'paid_gateway','sensitive_restricted', 'partial','Gateway a pagamento, accesso per pratica, audit obbligatorio.'),
  ('F16', 'PVP - Portale Vendite Pubbliche',                            'https://pvp.giustizia.it/',                                                      'giornaliera','public_file', 'public', 'partial',       'Aste e vendite forzate, scraping Firecrawl con filtro Padova.'),
  ('F19', 'Necrologi - DISABILITATO per privacy',                       NULL,                                                                              NULL,         'scraping',    'sensitive_restricted', 'disabled','Lock a livello DB: obituaries_seen_locked e obituaries_sources_locked. Non riabilitare senza policy review.'),
  ('F21', 'Portali immobiliari aggregati (Casa.it/Idealista/Subito)',   NULL,                                                                              'on_demand',  'scraping',    'sensitive_aggregate',  'partial','Solo conteggi/medie di zona via portalScrapers. No PII, no contatti.')
ON CONFLICT (source_code) DO NOTHING;