-- TrovaBandi: CCIAA Centro-Sud + BUR restanti + provincia/CM + GAL Campania
-- + enti nazionali Bandiora ancora assenti.
-- Domini CCIAA dall'elenco ufficiale Unioncamere
-- https://unioncamere.gov.it/sistema-camerale/elenco-delle-camere-di-commercio-italiane
-- Listing verificate live (HTTP 200, o contenuto ufficiale recuperato) il 22 Aug 2026.
-- Nessun nuovo cron, nessun secret, nessuna opportunity inventata, nessun Comune.
-- Non duplica official_domain già in produzione (CCIAA Nord-Toscana, BUR Nord,
-- provincia/CM già live, Padova albo).
-- Entità senza pagina listing live confermata: omesse (elenco nel PR).
-- Non ritentare collect su bur.regione.fvg.it (hang noto; già presente).

INSERT INTO public.trovabandi_sources
  (name, authority_level, region, province, official_domain, search_query, enabled, priority, source_kind, scan_interval_minutes, next_scan_at)
VALUES
  -- CCIAA Centro-Sud (Unioncamere)
  ('CCIAA Agrigento — bandi e contributi', 'CAMERALE', 'Sicilia', 'AG', 'ag.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Bari — bandi e contributi', 'CAMERALE', 'Puglia', 'BA', 'ba.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Basilicata — bandi e contributi', 'CAMERALE', 'Basilicata', 'PZ', 'basilicata.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Brindisi-Taranto — bandi e contributi', 'CAMERALE', 'Puglia', 'TA', 'brta.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Cagliari-Oristano — bandi e contributi', 'CAMERALE', 'Sardegna', 'CA', 'caor.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Caltanissetta — bandi e contributi', 'CAMERALE', 'Sicilia', 'CL', 'cameracommercio.cl.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Caserta — bandi e contributi', 'CAMERALE', 'Campania', 'CE', 'ce.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Catanzaro-Crotone-Vibo Valentia — bandi', 'CAMERALE', 'Calabria', 'CZ', 'czkrvv.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Chieti-Pescara — bandi e contributi', 'CAMERALE', 'Abruzzo', 'CH', 'chpe.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Cosenza — bandi e contributi', 'CAMERALE', 'Calabria', 'CS', 'cs.camcom.gov.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Foggia — bandi e contributi', 'CAMERALE', 'Puglia', 'FG', 'fg.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Frosinone-Latina — bandi e contributi', 'CAMERALE', 'Lazio', 'LT', 'frlt.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Gran Sasso d''Italia — bandi e contributi', 'CAMERALE', 'Abruzzo', 'AQ', 'cameragransasso.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Irpinia-Sannio — bandi e contributi', 'CAMERALE', 'Campania', 'AV', 'irpiniasannio.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Lecce — bandi e contributi', 'CAMERALE', 'Puglia', 'LE', 'le.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Marche — bandi e contributi', 'CAMERALE', 'Marche', 'AN', 'marche.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Messina — bandi e contributi', 'CAMERALE', 'Sicilia', 'ME', 'me.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Molise — bandi e contributi', 'CAMERALE', 'Molise', 'CB', 'molise.camcom.gov.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Napoli — bandi e contributi', 'CAMERALE', 'Campania', 'NA', 'na.camcom.gov.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Nuoro — bandi e contributi', 'CAMERALE', 'Sardegna', 'NU', 'nu.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Palermo-Enna — bandi e contributi', 'CAMERALE', 'Sicilia', 'PA', 'paen.camcom.gov.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Reggio Calabria — bandi e contributi', 'CAMERALE', 'Calabria', 'RC', 'rc.camcom.gov.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Rieti-Viterbo — bandi e contributi', 'CAMERALE', 'Lazio', 'VT', 'rivt.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Roma — bandi e contributi', 'CAMERALE', 'Lazio', 'RM', 'rm.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Salerno — bandi e contributi', 'CAMERALE', 'Campania', 'SA', 'sa.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Sassari — bandi e contributi', 'CAMERALE', 'Sardegna', 'SS', 'ss.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Sud Est Sicilia — bandi e contributi', 'CAMERALE', 'Sicilia', 'CT', 'ctrgsr.camcom.gov.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Trapani — bandi e contributi', 'CAMERALE', 'Sicilia', 'TP', 'tp.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),
  ('CCIAA Umbria — bandi e contributi', 'CAMERALE', 'Umbria', 'PG', 'umbria.camcom.it',
   'bandi contributi voucher imprese domande aperte', true, 90, 'CATALOGO', 60, now()),

  -- BUR / bollettini ufficiali restanti (Veneto→Toscana già presenti)
  ('Bollettino Ufficiale Regione Lazio — BUR', 'REGIONALE', 'Lazio', NULL, 'regione.lazio.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Marche', 'REGIONALE', 'Marche', NULL, 'bur.regione.marche.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Umbria', 'REGIONALE', 'Umbria', NULL, 'bur.regione.umbria.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Abruzzo — BURA', 'REGIONALE', 'Abruzzo', NULL, 'bura.regione.abruzzo.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Campania — BURC', 'REGIONALE', 'Campania', NULL, 'burc.regione.campania.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Puglia — BURP', 'REGIONALE', 'Puglia', NULL, 'burp.regione.puglia.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Basilicata — BURB', 'REGIONALE', 'Basilicata', NULL, 'regione.basilicata.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),
  ('Bollettino Ufficiale Regione Sardegna — BURAS', 'REGIONALE', 'Sardegna', NULL, 'buras.regione.sardegna.it',
   'DGR allegato bando contributi imprese fondo perduto apertura domande', true, 100, 'BUR', 60, now()),

  -- Provincia / Città metropolitana (listing sovvenzioni o bandi/avvisi live)
  ('Provincia di Perugia — sovvenzioni e contributi', 'REGIONALE', 'Umbria', 'PG', 'provincia.perugia.it',
   'sovvenzioni contributi sussidi bandi imprese associazioni domande aperte', true, 97, 'CATALOGO', 60, now()),
  ('Provincia di Benevento — sovvenzioni e contributi', 'REGIONALE', 'Campania', 'BN', 'provincia.benevento.it',
   'sovvenzioni contributi sussidi bandi imprese associazioni domande aperte', true, 97, 'CATALOGO', 60, now()),
  ('Provincia di Fermo — sovvenzioni e contributi', 'REGIONALE', 'Marche', 'FM', 'provincia.fermo.it',
   'sovvenzioni contributi sussidi bandi imprese associazioni domande aperte', true, 97, 'CATALOGO', 60, now()),
  ('Provincia di Pesaro e Urbino — sovvenzioni e contributi', 'REGIONALE', 'Marche', 'PU', 'casadivetro.provincia.pu.it',
   'sovvenzioni contributi sussidi bandi imprese associazioni domande aperte', true, 97, 'CATALOGO', 60, now()),
  ('Città Metropolitana di Cagliari — bandi e avvisi', 'REGIONALE', 'Sardegna', 'CA', 'cittametropolitanacagliari.it',
   'sovvenzioni contributi sussidi bandi imprese associazioni domande aperte', true, 97, 'CATALOGO', 60, now()),

  -- GAL Campania 2023-2027 (siti dall'elenco ufficiale PSR Campania Comunica;
  -- solo quelli con pagina bandi/avvisi live sullo stesso dominio)
  ('GAL Casacastra', 'COMUNALE', 'Campania', 'SA', 'galcasacastra.it',
   'nuovo bando pubblico imprese contributo fondo perduto prossima pubblicazione', true, 98, 'GAL', 60, now()),
  ('GAL Cilento', 'COMUNALE', 'Campania', 'SA', 'galcilento.it',
   'nuovo bando pubblico imprese contributo fondo perduto prossima pubblicazione', true, 98, 'GAL', 60, now()),
  ('GAL I Sentieri del Buon Vivere', 'COMUNALE', 'Campania', 'SA', 'sentieridelbuonvivere.it',
   'nuovo bando pubblico imprese contributo fondo perduto prossima pubblicazione', true, 98, 'GAL', 60, now()),
  ('GAL Partenio', 'COMUNALE', 'Campania', 'AV', 'galpartenio.it',
   'nuovo bando pubblico imprese contributo fondo perduto prossima pubblicazione', true, 98, 'GAL', 60, now()),
  ('GAL Terra è Vita', 'COMUNALE', 'Campania', 'SA', 'galterraevita.eu',
   'nuovo bando pubblico imprese contributo fondo perduto prossima pubblicazione', true, 98, 'GAL', 60, now()),
  ('GAL Vesuvio Verde', 'COMUNALE', 'Campania', 'NA', 'galvesuvioverde.it',
   'nuovo bando pubblico imprese contributo fondo perduto prossima pubblicazione', true, 98, 'GAL', 60, now()),

  -- Nazionali Bandiora ancora assenti
  ('INAIL — incentivi ISI alle imprese', 'NAZIONALE', NULL, NULL, 'inail.it',
   'bando ISI incentivi imprese sicurezza domande aperte', true, 95, 'CATALOGO', 60, now()),
  ('ICE Agenzia — contributi e finanziamenti', 'NAZIONALE', NULL, NULL, 'ice.it',
   'contributi internazionalizzazione imprese bandi domande', true, 94, 'CATALOGO', 60, now()),
  ('Fondimpresa — avvisi Conto di Sistema', 'NAZIONALE', NULL, NULL, 'fondimpresa.it',
   'avvisi conto di sistema formazione imprese domande aperte', true, 93, 'CATALOGO', 60, now()),
  ('SIMEST — finanziamenti agevolati', 'NAZIONALE', NULL, NULL, 'simest.it',
   'finanziamenti agevolati internazionalizzazione imprese domande', true, 94, 'CATALOGO', 60, now()),
  ('GSE — bandi e avvisi pubblici', 'NAZIONALE', NULL, NULL, 'gse.it',
   'bandi incentivi rinnovabili imprese avvisi pubblici', true, 93, 'CATALOGO', 60, now())
ON CONFLICT (official_domain, search_query) DO UPDATE SET
  name = EXCLUDED.name,
  authority_level = EXCLUDED.authority_level,
  region = EXCLUDED.region,
  province = EXCLUDED.province,
  enabled = true,
  priority = EXCLUDED.priority,
  source_kind = EXCLUDED.source_kind,
  scan_interval_minutes = EXCLUDED.scan_interval_minutes,
  next_scan_at = now(),
  updated_at = now();
